export const BOOK_TITLE = {
    UB: 'Urantia Book',
    BOM: 'Book of Mormon',
    BIBLE: 'Bible'
};

export const TABLES_OF_CONTENTS = {
    UB: [
        // Foreword had to be hardcoded
        {
            part: 1,
            title: "Part I. The Central and Superuniverses",
            text: "Sponsored by a Uversa Corps of Superuniverse Personalities acting by authority of the Orvonton Ancients of Days",
            papers: [
                { paper: 1, title: "The Universal Father", sections: 7 },
                { paper: 2, title: "The Nature of God", sections: 7 },
                { paper: 3, title: "The Attributes of God", sections: 6 },
                { paper: 4, title: "God's Relation to the Universe", sections: 5 },
                { paper: 5, title: "God's Relation to the Individual", sections: 6 },
                { paper: 6, title: "The Eternal Son", sections: 8 },
                { paper: 7, title: "Relation of the Eternal Son to the Universe", sections: 7 },
                { paper: 8, title: "The Infinite Spirit", sections: 6 },
                { paper: 9, title: "Relation of the Infinite Spirit to the Universe", sections: 8 },
                { paper: 10, title: "The Paradise Trinity", sections: 8 },
                { paper: 11, title: "The Eternal Isle of Paradise", sections: 9 },
                { paper: 12, title: "The Universe of Universes", sections: 9 },
                { paper: 13, title: "The Sacred Spheres of Paradise", sections: 4 },
                { paper: 14, title: "The Central and Divine Universe", sections: 6 },
                { paper: 15, title: "The Seven Superuniverses", sections: 14 },
                { paper: 16, title: "The Seven Master Spirits", sections: 9 },
                { paper: 17, title: "The Seven Supreme Spirit Groups", sections: 8 },
                { paper: 18, title: "The Supreme Trinity Personalities", sections: 7 },
                { paper: 19, title: "The Co-ordinate Trinity-Origin Beings", sections: 7 },
                { paper: 20, title: "The Paradise Sons of God", sections: 10 },
                { paper: 21, title: "The Paradise Creator Sons", sections: 6 },
                { paper: 22, title: "The Trinitized Sons of God", sections: 10 },
                { paper: 23, title: "The Solitary Messengers", sections: 4 },
                { paper: 24, title: "Higher Personalities of the Infinite Spirit", sections: 7 },
                { paper: 25, title: "The Messenger Hosts of Space", sections: 8 },
                { paper: 26, title: "Ministering Spirits of the Central Universe", sections: 11 },
                { paper: 27, title: "Ministry of the Primary Supernaphim", sections: 7 },
                { paper: 28, title: "Ministering Spirits of the Superuniverses", sections: 7 },
                { paper: 29, title: "The Universe Power Directors", sections: 5 },
                { paper: 30, title: "Personalities of the Grand Universe", sections: 4 },
                { paper: 31, title: "The Corps of the Finality", sections: 10 },
            ]
        },
        {
            part: 2,
            title: "Part II. The Local Universe",
            text: "Sponsored by a Nebadon Corps of Local Universe Personalities acting by authority of Gabriel of Salvington",
            papers: [
                { paper: 32, title: "The Evolution of the Local Universe", sections: 5 },
                { paper: 33, title: "Administration of the Local Universe", sections: 8 },
                { paper: 34, title: "The Local Universe Mother Spirit", sections: 7 },
                { paper: 35, title: "The Local Universe Sons of God", sections: 10 },
                { paper: 36, title: "The Life Carriers", sections: 6 },
                { paper: 37, title: "Personalities of the Local Universe", sections: 10 },
                { paper: 38, title: "Ministering Spirits of the Local Universe", sections: 9 },
                { paper: 39, title: "The Seraphic Hosts", sections: 9 },
                { paper: 40, title: "The Ascending Sons of God", sections: 10 },
                { paper: 41, title: "Physical Aspects of the Local Universe", sections: 10 },
                { paper: 42, title: "Energy — Mind and Matter", sections: 12 },
                { paper: 43, title: "The Constellations", sections: 9 },
                { paper: 44, title: "The Celestial Artisans", sections: 8 },
                { paper: 45, title: "The Local System Administration", sections: 7 },
                { paper: 46, title: "The Local System Headquarters", sections: 8 },
                { paper: 47, title: "The Seven Mansion Worlds", sections: 10 },
                { paper: 48, title: "The Morontia Life", sections: 8 },
                { paper: 49, title: "The Inhabited Worlds", sections: 6 },
                { paper: 50, title: "The Planetary Princes", sections: 7 },
                { paper: 51, title: "The Planetary Adams", sections: 7 },
                { paper: 52, title: "Planetary Mortal Epochs", sections: 7 },
                { paper: 53, title: "The Lucifer Rebellion", sections: 9 },
                { paper: 54, title: "Problems of the Lucifer Rebellion", sections: 6 },
                { paper: 55, title: "The Spheres of Light and Life", sections: 12 },
                { paper: 56, title: "Universal Unity", sections: 10 },
            ]
        },
        {
            part: 3,
            title: "Part III. The History of Urantia",
            text: "These papers were sponsored by a Corps of Local Universe Personalities acting by authority of Gabriel of Salvington",
            papers: [
                { paper: 57, title: "The Origin of Urantia", sections: 8 },
                { paper: 58, title: "Life Establishment on Urantia", sections: 7},
                { paper: 59, title: "The Marine-Life Era on Urantia", sections: 6},
                { paper: 60, title: "Urantia During the Early Land-Life Era", sections: 4},
                { paper: 61, title: "The Mammalian Era on Urantia", sections: 7},
                { paper: 62, title: "The Dawn Races of Early Man", sections: 7},
                { paper: 63, title: "The First Human Family", sections: 7},
                { paper: 64, title: "The Evolutionary Races of Color", sections: 7},
                { paper: 65, title: "The Overcontrol of Evolution", sections: 8},
                { paper: 66, title: "The Planetary Prince of Urantia", sections: 8},
                { paper: 67, title: "The Planetary Rebellion", sections: 8},
                { paper: 68, title: "The Dawn of Civilization", sections: 6},
                { paper: 69, title: "Primitive Human Institutions", sections: 9},
                { paper: 70, title: "The Evolution of Human Government", sections: 12},
                { paper: 71, title: "Development of the State", sections: 8},
                { paper: 72, title: "Government on a Neighboring Planet", sections: 12},
                { paper: 73, title: "The Garden of Eden", sections: 7},
                { paper: 74, title: "Adam and Eve", sections: 8},
                { paper: 75, title: "The Default of Adam and Eve", sections: 8},
                { paper: 76, title: "The Second Garden", sections: 6},
                { paper: 77, title: "The Midway Creatures", sections: 9},
                { paper: 78, title: "The Violet Race after the Days of Adam", sections: 8},
                { paper: 79, title: "Andite Expansion in the Orient", sections: 8},
                { paper: 80, title: "Andite Expansion in the Occident", sections: 9},
                { paper: 81, title: "Development of Modern Civilization", sections: 6},
                { paper: 82, title: "The Evolution of Marriage", sections: 6},
                { paper: 83, title: "The Marriage Institution", sections: 8},
                { paper: 84, title: "Marriage and Family Life", sections: 8},
                { paper: 85, title: "The Origins of Worship", sections: 7},
                { paper: 86, title: "Early Evolution of Religion", sections: 7},
                { paper: 87, title: "The Ghost Cults", sections: 7},
                { paper: 88, title: "Fetishes, Charms, and Magic", sections: 6},
                { paper: 89, title: "Sin, Sacrifice, and Atonement", sections: 10},
                { paper: 90, title: "Shamanism — Medicine Men and Priests", sections: 5},
                { paper: 91, title: "The Evolution of Prayer", sections: 9},
                { paper: 92, title: "The Later Evolution of Religion", sections: 7},
                { paper: 93, title: "Machiventa Melchizedek", sections: 10},
                { paper: 94, title: "The Melchizedek Teachings in the Orient", sections: 12},
                { paper: 95, title: "The Melchizedek Teachings in the Levant", sections: 7},
                { paper: 96, title: "Yahweh — God of the Hebrews", sections: 7},
                { paper: 97, title: "Evolution of the God Concept among the Hebrews", sections: 10},
                { paper: 98, title: "The Melchizedek Teachings in the Occident", sections: 7},
                { paper: 99, title: "The Social Problems of Religion", sections: 7},
                { paper: 100, title: "Religion in Human Experience", sections: 7},
                { paper: 101, title: "The Real Nature of Religion", sections: 10},
                { paper: 102, title: "The Foundations of Religious Faith", sections: 8},
                { paper: 103, title: "The Reality of Religious Experience", sections: 9},
                { paper: 104, title: "Growth of the Trinity Concept", sections: 5},
                { paper: 105, title: "Deity and Reality", sections: 7},
                { paper: 106, title: "Universe Levels of Reality", sections: 9},
                { paper: 107, title: "Origin and Nature of Thought Adjusters", sections: 7},
                { paper: 108, title: "Mission and Ministry of Thought Adjusters", sections: 6},
                { paper: 109, title: "Relation of Adjusters to Universe Creatures", sections: 7},
                { paper: 110, title: "Relation of Adjusters to Individual Mortals", sections: 7},
                { paper: 111, title: "The Adjuster and the Soul", sections: 7},
                { paper: 112, title: "Personality Survival", sections: 7},
                { paper: 113, title: "Seraphic Guardians of Destiny", sections: 7},
                { paper: 114, title: "Seraphic Planetary Government", sections: 7},
                { paper: 115, title: "The Supreme Being", sections: 7},
                { paper: 116, title: "The Almighty Supreme", sections: 7},
                { paper: 117, title: "God the Supreme", sections: 7},
                { paper: 118, title: "Supreme and Ultimate — Time and Space", sections: 10},
                { paper: 119, title: "The Bestowals of Christ Michael", sections: 8},
            ]
        },
        {
            part: 4,
            title: "Part IV. The Life and Teachings of Jesus",
            text:   
                "This group of papers was sponsored by a commission of twelve Urantia midwayers acting under the supervision of a Melchizedek revelatory director. The basis of this narrative was supplied by a secondary midwayer who was onetime assigned to the superhuman watchcare of the Apostle Andrew.",
            papers: [
                { paper: 120, title: "The Bestowal of Michael on Urantia", sections: 4 },
                { paper: 121, title: "The Times of Michael's Bestowal", sections: 8},
                { paper: 122, title: "Birth and Infancy of Jesus", sections: 10},
                { paper: 123, title: "The Early Childhood of Jesus", sections: 6},
                { paper: 124, title: "The Later Childhood of Jesus", sections: 6},
                { paper: 125, title: "Jesus at Jerusalem", sections: 6},
                { paper: 126, title: "The Two Crucial Years", sections: 5},
                { paper: 127, title: "The Adolescent Years", sections: 6},
                { paper: 128, title: "Jesus' Early Manhood", sections: 7},
                { paper: 129, title: "The Later Adult Life of Jesus", sections: 4},
                { paper: 130, title: "On the Way to Rome", sections: 8},
                { paper: 131, title: "The World's Religions", sections: 10},
                { paper: 132, title: "The Sojourn at Rome", sections: 7},
                { paper: 133, title: "The Return from Rome", sections: 9},
                { paper: 134, title: "The Transition Years", sections: 9},
                { paper: 135, title: "John the Baptist", sections: 12},
                { paper: 136, title: "Baptism and the Forty Days", sections: 10},
                { paper: 137, title: "Tarrying Time in Galilee", sections: 8},
                { paper: 138, title: "Training the Kingdom's Messengers", sections: 10},
                { paper: 139, title: "The Twelve Apostles", sections: 12},
                { paper: 140, title: "The Ordination of the Twelve", sections: 10},
                { paper: 141, title: "Beginning the Public Work", sections: 9},
                { paper: 142, title: "The Passover at Jerusalem", sections: 8},
                { paper: 143, title: "Going Through Samaria", sections: 7},
                { paper: 144, title: "At Gilboa and in the Decapolis", sections: 9},
                { paper: 145, title: "Four Eventful Days at Capernaum", sections: 5},
                { paper: 146, title: "First Preaching Tour of Galilee", sections: 7},
                { paper: 147, title: "The Interlude Visit to Jerusalem", sections: 8},
                { paper: 148, title: "Training Evangelists at Bethsaida", sections: 9},
                { paper: 149, title: "The Second Preaching Tour", sections: 7},
                { paper: 150, title: "The Third Preaching Tour", sections: 9},
                { paper: 151, title: "Tarrying and Teaching by the Seaside", sections: 6},
                { paper: 152, title: "Events Leading up to the Capernaum Crisis", sections: 7},
                { paper: 153, title: "The Crisis at Capernaum", sections: 5},
                { paper: 154, title: "Last Days at Capernaum", sections: 7},
                { paper: 155, title: "Fleeing Through Northern Galilee", sections: 6},
                { paper: 156, title: "The Sojourn at Tyre and Sidon", sections: 6},
                { paper: 157, title: "At Caesarea-Philippi", sections: 7},
                { paper: 158, title: "The Mount of Transfiguration", sections: 8},
                { paper: 159, title: "The Decapolis Tour", sections: 6},
                { paper: 160, title: "Rodan of Alexandria", sections: 5},
                { paper: 161, title: "Further Discussions with Rodan", sections: 3},
                { paper: 162, title: "At the Feast of Tabernacles", sections: 9},
                { paper: 163, title: "Ordination of the Seventy at Magadan", sections: 7},
                { paper: 164, title: "At the Feast of Dedication", sections: 5},
                { paper: 165, title: "Ordination of the Seventy at Magadan", sections: 6},
                { paper: 166, title: "Last Visit to Northern Perea", sections: 5},
                { paper: 167, title: "The Visit to Philadephia", sections: 7},
                { paper: 168, title: "The Resurrection of Lazarus", sections: 5},
                { paper: 169, title: "Last Teaching at Pella", sections: 4},
                { paper: 170, title: "The Kingdom of Heaven", sections: 5},
                { paper: 171, title: "On the Way to Jerusalem", sections: 8},
                { paper: 172, title: "Going into Jerusalem", sections: 5},
                { paper: 173, title: "Monday in Jerusalem", sections: 5},
                { paper: 174, title: "Tuesday Morning in the Temple", sections: 5},
                { paper: 175, title: "The Last Temple Discourse", sections: 4},
                { paper: 176, title: "Tuesday Evening on Mount Olivet", sections: 4},
                { paper: 177, title: "Wednesday, the Rest Day", sections: 5},
                { paper: 178, title: "Last Day at the Camp", sections: 3},
                { paper: 179, title: "The Last Supper", sections: 5},
                { paper: 180, title: "The Farewell Discourse", sections: 6},
                { paper: 181, title: "Final Admonitions and Warnings", sections: 2},
                { paper: 182, title: "In Gethsemane", sections: 3},
                { paper: 183, title: "The Betrayal and Arrest of Jesus", sections: 5},
                { paper: 184, title: "Before the Sanhedrin Court", sections: 5},
                { paper: 185, title: "The Trial Before Pilate", sections: 8},
                { paper: 186, title: "Just Before the Crucifixion", sections: 5},
                { paper: 187, title: "The Crucifixion", sections: 6},
                { paper: 188, title: "The Time of the Tomb", sections: 5},
                { paper: 189, title: "The Resurrection", sections: 5},
                { paper: 190, title: "Morontia Appearances of Jesus", sections: 5},
                { paper: 191, title: "Appearances to the Apostles and Other Leaders", sections: 6},
                { paper: 192, title: "Appearances in Galilee", sections: 4},
                { paper: 193, title: "Final Appearances and Ascension", sections: 6},
                { paper: 194, title: "Bestowal of the Spirit of Truth", sections: 4},
                { paper: 195, title: "After Pentecost", sections: 10},
                { paper: 196, title: "The Faith of Jesus", sections: 3},
            ]
        }
    ]
};